#!/bin/bash
#
# Configure storage locations for sushi pipeline
# Handles both local storage (on sushi) and network drives
#

set -e

SUSHI_DIR="$(cd "$(dirname "$0")" && pwd)"
STORAGE_CONF="$SUSHI_DIR/config/storage.conf"

echo "========================================"
echo "  Sushi Storage Configuration"
echo "========================================"
echo ""

# Detect if we're on Mac or Linux (sushi)
if [[ "$OSTYPE" == "darwin"* ]]; then
    IS_MAC=true
    echo "Platform: Mac (accessing sushi via network)"
else
    IS_MAC=false
    echo "Platform: Linux (running on sushi)"
fi

echo ""
echo "Available storage options:"
echo ""

if [ "$IS_MAC" = true ]; then
    # Mac options
    echo "1. Local (in repo) - For testing only"
    echo "   Location: $SUSHI_DIR/videos"
    echo ""
    echo "2. Network: home-meera"
    echo "   Location: /Volumes/home-meera/earninglens-videos"

    if mount | grep -q "192.168.1.101/home-meera"; then
        echo "   Status: ✓ Mounted"
        AVAILABLE=$(df -h /Volumes/home-meera | awk 'NR==2 {print $4}')
        echo "   Available: $AVAILABLE"
    else
        echo "   Status: ✗ Not mounted"
    fi

    echo ""
    echo "3. Network: var-data"
    echo "   Location: /Volumes/var-data/earninglens-videos"

    if mount | grep -q "192.168.1.101/var-data"; then
        echo "   Status: ✓ Mounted"
        AVAILABLE=$(df -h /Volumes/var-data | awk 'NR==2 {print $4}')
        echo "   Available: $AVAILABLE"
    else
        echo "   Status: ✗ Not mounted"
        echo ""
        echo "   To mount: open smb://192.168.1.101/var-data in Finder"
    fi
else
    # Sushi options
    echo "1. Local (in repo) - For testing only"
    echo "   Location: $SUSHI_DIR/videos"
    echo ""
    echo "2. /home/meera/earninglens-videos"

    if [ -d "/home/meera" ]; then
        echo "   Status: ✓ Available"
        AVAILABLE=$(df -h /home/meera | awk 'NR==2 {print $4}')
        echo "   Available: $AVAILABLE"
    else
        echo "   Status: ✗ Not found"
    fi

    echo ""
    echo "3. /var/data/earninglens-videos (RECOMMENDED)"

    if [ -d "/var/data" ]; then
        echo "   Status: ✓ Available"
        AVAILABLE=$(df -h /var/data | awk 'NR==2 {print $4}')
        echo "   Available: $AVAILABLE"
    else
        echo "   Status: ✗ Not found"
    fi
fi

echo ""
echo "========================================"
echo ""

# Interactive selection
read -p "Choose storage location (1/2/3): " choice

case $choice in
    1)
        VIDEOS_BASE_DIR="$SUSHI_DIR/videos"
        ;;
    2)
        if [ "$IS_MAC" = true ]; then
            VIDEOS_BASE_DIR="/Volumes/home-meera/earninglens-videos"
        else
            VIDEOS_BASE_DIR="/home/meera/earninglens-videos"
        fi
        ;;
    3)
        if [ "$IS_MAC" = true ]; then
            VIDEOS_BASE_DIR="/Volumes/var-data/earninglens-videos"
        else
            VIDEOS_BASE_DIR="/var/data/earninglens-videos"
        fi
        ;;
    *)
        echo "Invalid choice. Using default (in repo)."
        VIDEOS_BASE_DIR="$SUSHI_DIR/videos"
        ;;
esac

echo ""
echo "Selected: $VIDEOS_BASE_DIR"

# Create directory if it doesn't exist
if [ ! -d "$VIDEOS_BASE_DIR" ]; then
    echo ""
    read -p "Directory doesn't exist. Create it? (y/n): " create
    if [ "$create" = "y" ]; then
        mkdir -p "$VIDEOS_BASE_DIR"
        echo "✓ Created: $VIDEOS_BASE_DIR"
    else
        echo "❌ Directory must exist. Exiting."
        exit 1
    fi
else
    echo "✓ Directory exists"
fi

# Update storage.conf
echo ""
echo "Updating $STORAGE_CONF..."

cat > "$STORAGE_CONF" <<EOF
# Storage Configuration for Sushi Pipeline
# Auto-generated by setup-storage.sh on $(date)

# Videos storage location
VIDEOS_BASE_DIR="$VIDEOS_BASE_DIR"

# Logs location
LOGS_DIR="$SUSHI_DIR/logs"

# Temp directory for processing
TEMP_DIR="$SUSHI_DIR/.tmp"

# Export for use in scripts
export VIDEOS_BASE_DIR
export LOGS_DIR
export TEMP_DIR
EOF

echo "✓ Configuration saved"

# Create symlink for convenience
echo ""
if [ ! -L "$SUSHI_DIR/videos" ] && [ "$VIDEOS_BASE_DIR" != "$SUSHI_DIR/videos" ]; then
    read -p "Create symlink: sushi/videos -> $VIDEOS_BASE_DIR? (y/n): " symlink
    if [ "$symlink" = "y" ]; then
        # Remove old directory if empty
        if [ -d "$SUSHI_DIR/videos" ] && [ -z "$(ls -A $SUSHI_DIR/videos)" ]; then
            rmdir "$SUSHI_DIR/videos"
        fi

        ln -sf "$VIDEOS_BASE_DIR" "$SUSHI_DIR/videos"
        echo "✓ Symlink created: sushi/videos -> $VIDEOS_BASE_DIR"
    fi
fi

# Test write access
echo ""
echo "Testing write access..."
TEST_FILE="$VIDEOS_BASE_DIR/.write_test"
if touch "$TEST_FILE" 2>/dev/null; then
    rm "$TEST_FILE"
    echo "✓ Write access confirmed"
else
    echo "❌ No write access to $VIDEOS_BASE_DIR"
    echo "   Check permissions"
    exit 1
fi

echo ""
echo "========================================"
echo "✓ Storage configuration complete!"
echo "========================================"
echo ""
echo "Videos will be stored in:"
echo "  $VIDEOS_BASE_DIR"
echo ""
echo "To change later, run: ./setup-storage.sh"
echo ""
